### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/dhbw-timetable-android#12]
Design and implement a dark theme

**Comment by hendriku** [comment]
@MalteBartels Sag bescheid wenn du eine Farbkomposition für das DarkTheme hast. :)

**Comment by MalteBartels** [comment]
@hendriku Update: Currently working on the colors

**Comment by MalteBartels** [comment]
@hendriku So here's what I think:
First of all, the dark theme should talk the same language, especially considering colours. However, it should be notably different, too, so not just changing the background color to a dark blue or grey.

In my opinion, there are basically two ways of achieving this, with different ideas in mind:
1. Wie implement this as a night mode. Purpose: Not burning your retina at night, in consequence all colours would be quite dark, especially in modals. This would of course make it difficult to read in bright sunlight.
2. Just another theme for the app, to fit your personal style. In this case, the colours should pop as they do (or will do) in light theme. User's would recognise it as our app, but it would look as different as possible.

Do you think, we should chose one of these and start right ahead or just try to sketch both roughly and decide afterwards? (I would prefer the last one)

**Comment by hendriku** [comment]
@MalteBartels It would be wonderful if you could design mockups for each those options. If yes, it would be much easier to decide how we should go on.

**Comment by MalteBartels** [comment]
@hendriku Have a look on [sketch cloud,](https://sketch.cloud/s/VaAg/p/timetable-basics) there's an early idea of how a dark theme could look.

**Comment by hendriku** [comment]
@MalteBartels Hey looks cool. Can you update the few things we discussed last time? When we approve the design I just need the color and we can go dark 😎

**Comment by hendriku** [comment]
Dark theme is not any longer planned for beta.

**Comment by MalteBartels** [comment]
As we're now discussing colors and various themes in general, I'm gonna open a new issue for themes.

So have a look here: #37 Different themes
