### ISSUE TITLE
Approve responsive design

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/dhbw-timetable-android#13]
Check if design responds correctly to different devices

**Comment by hendriku** [comment]
Google Pixel XL
![image](https://cloud.githubusercontent.com/assets/8998518/26375703/412f2e7e-400a-11e7-95d8-cc262c5f5272.png)

1. Round edges are not round enough
2. Text size is way to low

**Comment by hendriku** [comment]
This is now fixed. Further tests following.

**Comment by MalteBartels** [comment]
@hendriku Could you add some more screenshots to explain what changed? And what happens in landscape?

**Comment by hendriku** [comment]
![screenshot_20170526-122422](https://cloud.githubusercontent.com/assets/8998518/26490912/9dfb2252-420d-11e7-84da-714d86049d20.png)
![screenshot_20170526-122413](https://cloud.githubusercontent.com/assets/8998518/26490915/9ec3ab46-420d-11e7-9bb8-20716d613513.png)
Taken from a smaller screen but the content (rectangles and text) will scale through device pixel value.
This means the amount of content will be exaclty the same for phones with higher screen size which is not perfect (e.g. friday will still be hidden via scroll on landscape) but should propably be okay for cupcake.

**Comment by hendriku** [comment]
There were no further issues on several devices so this is fixed now for beta.
