### ISSUE TITLE
Onboarding experience

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/dhbw-timetable-android#21]
We should define how the first experience for the user has to be. It has to be error free and more intuitive than this:

![image](https://cloud.githubusercontent.com/assets/8998518/26374462/b80aa80c-4005-11e7-953c-0af872f2a780.png)

**Comment by hendriku** [comment]
Also think about the default preferences.

**Comment by hendriku** [comment]
Onboard experience is way better now, default preferences are implemented but possibly not perfect. Currently, implementation of the tutorial is missing.

**Comment by hendriku** [comment]
@MalteBartels Please check out latest version of the app and evaluate the first experience for the user.

**Comment by hendriku** [comment]
@MalteBartels For your information
![screenshot_1495646095](https://cloud.githubusercontent.com/assets/8998518/26416182/4c31fc06-40b5-11e7-97b7-9c17840ff25b.png)

**Comment by MalteBartels** [comment]
I like it. Should be enough for our cupcake, maybe we might revisit this in midterm;)

**Comment by hendriku** [comment]
Okay I will close this issue for cupcake
