### ISSUE TITLE
GitHub Page for information

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/dhbw-timetable-android#22]
Goal is to develop a basic PR website which will be available through QR code.
# Content
- Screenshots with related...
- ...Features 
- Author and legal info ("about us" description)
- Link to repository

**Comment by MalteBartels** [comment]
@hendriku Do you want to make a material design page or should we use this basic everything is centric style website everyone uses? (Like my Hawaii Website)

**Comment by hendriku** [comment]
Well flat design based would be awesome. No complicated pictures but light screenshots with feature descriptions. I think there's nothing against centric style website so just do a mockup.

**Comment by MalteBartels** [comment]
Website can now be found here: https://dhbw-timetable.github.io/dhbw-timetable-android/

Could you link this in the description please, @hendriku ?
