### ISSUE TITLE
Branch for design sketches?

### ISSUE THREAD

**Issue by MalteBartels** [dhbw-timetable/dhbw-timetable-android#26]
I hope to start soon with some designs sketches for the dark theme and mid-term improvements. Do you think it makes sense to create a branch to have them in one place? @hendriku

**Comment by hendriku** [comment]
Yeah this makes sense in my opinion. Just make sure you do not merge with master as it would be confusing to have code and design in same folder.

**Comment by MalteBartels** [comment]
I will present my designs via sketch cloud here: https://sketch.cloud/s/VaAg/p/timetable-basics/
