### ISSUE TITLE
Week summary view for next week

### ISSUE THREAD

**Issue by hendriku** [dhbw-timetable/dhbw-timetable-android#40]
Week view should show on saturday already the week summary of the next week as this week is not any longer relevant.

@MalteBartels Do you like this idea?

**Comment by MalteBartels** [comment]
Yeah, makes sense, but it should be clear that it is the next week and not the current week as usual.

**Comment by hendriku** [comment]
So lets rename the header to "Next Week" for weekends?

**Comment by hendriku** [comment]
Done.
