### ISSUE TITLE
Day View Mode

### ISSUE THREAD

**Issue by ghost** [dhbw-timetable/dhbw-timetable-android#96]
I noticed that there is already a Two Day View
I would like to know if there will be a Day View like this? 
![screenshot_2018-01-08-04-33-30](https://user-images.githubusercontent.com/8343955/35198339-a6bdce22-ff17-11e7-84b2-efb23fb3b06d.png)

**Comment by hendriku** [comment]
Hi @devoma ! At this time we provide a ["Today" view](https://lh3.googleusercontent.com/pdxQemi_riCcsgPe0QXu-60n-6aC6RP4zyp2m-UxPcR546vWBs09BzRvhkBadER23s4=h900) with the events&breaks of the current day and a short summary for tomorrow. Additionally there's a ["Week" view](https://lh3.googleusercontent.com/hdeode0wsjokzgrHJNUhSuRn9_CGqZKlkRTHjtrEH9Kr-otJDuipG4EKNjxafGKw5G8=h900) looking similar to the screenshot you posted. But if you scroll horizontally there will be all the events of the whole week.

However, we experienced that our "Today" view is not that capable for parallel lectures, so we will have to change it in the future... We are currently trying to find some suitable design and are open for any feedback or suggestions! 😺
